print("First Timestamp")
h1 = input("Enter hours: ")
m1 = input("Enter minutes: ")
s1 = input("Enter seconds: ")
print("Second Timestamp")
h2 = input("Enter hours: ")
m2 = input("Enter minutes: ")
s2 = input("Enter seconds: ")
sum1 = int(int(h1) * 3600) + int(int(m1) * 60) + int(s1)
sum2 = int(int(h2) * 3600) + int(int(m2) * 60) + int(s2)
print(int(sum2) - int(sum1))